[tool.poetry]
name = "awesomemakefile"
version = "0.1.0"
description = "Just simple project to try Makefile"
authors = ["Sasha-nice <borisov.al.an@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
